version: "3.7"

services:
  opensearch-1:
    image: opensearchproject/opensearch:2.14.0
    container_name: opensearch-1
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Halwany@123
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  opensearch-dashboards-1:
    image: opensearchproject/opensearch-dashboards:2.14.0
    container_name: opensearch-dashboards-1
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch-1:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true

volumes:
  opensearch-data:
